# Copyright 2026 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test an "attach" failure in DAP.

require allow_dap_tests

load_lib dap-support.exp

standard_testfile attach.c

if {[build_executable ${testfile}.exp $testfile $srcfile] == -1} {
    return
}

# Attaching to PID 1 should always fail.
set attach_id [dap_attach 1 $binfile]

dap_check_request_and_response "configurationDone" configurationDone

set resp [lindex [dap_read_response attach $attach_id] 0]
gdb_assert {[dict get $resp success] == "false"} \
    "attach failed"

dap_shutdown
