#!/bin/sh

# Usage: ./contrib/setup

dir=`git rev-parse --git-dir`

test -d "$dir" || {
    echo "setup: could not find .git directory" 1>&2
    echo "This script is only useful with a git clone" 1>&2
    exit 1
}

test -d "$dir"/hooks || {
    echo "setup: could not find $dir/hooks directory" 1>&2
    exit 1
}

if test -f $dir/hooks/prepare-commit-msg; then
    echo "setup: $dir/hooks/prepare-commit-msg already exists" 1>&2
    echo "Maybe you already ran this script, or maybe you need to chain" 1>&2
    echo "your existing script with ./contrib/prepare-commit-msg" 1>&2
    exit 1
fi

set -e
cp ./contrib/prepare-commit-msg $dir/hooks/prepare-commit-msg
chmod u+x $dir/hooks/prepare-commit-msg

echo "New commits will now automatically get a Patch-ID tag."
echo "If you preserve these across changes, the patch tracker will work better."
